Object.assign(
  exports,
  require("./src/callables/chart"),
  require("./src/callables/chat"),
  require("./src/callables/horoscope"),
  require("./src/callables/tarot"),
  require("./src/callables/geomancy"),
  require("./src/callables/compatibility"),
  require("./src/callables/social"),
  require("./src/callables/places"),
  require("./src/callables/account"),
  require("./src/callables/monetization"),
  require("./src/callables/rewards"),
  require("./src/scheduled/notifications")
);
