Object.assign(
  exports,
  require("./src/callables/chart"),
  require("./src/callables/chat"),
  require("./src/callables/horoscope"),
  require("./src/callables/tarot"),
  require("./src/callables/geomancy"),
  require("./src/callables/compatibility"),
  require("./src/callables/places")
);
