const List<String> randomPrompts = [
  'Am I avoiding success or failure?',
  'Am I on the right career path?',
  'Is this attraction emotional, karmic, or temporary?',
  'Is this ending actually protecting me?',
  'Is this person good for my growth or just familiar?',
  'Should I distance myself from this person?',
  'Should I reach out or stay silent?',
  'Should I take the risk or wait?',
  'Should I wait, speak, or walk away?',
  'Was this love, attachment, or unfinished karma?',
  'What am I addicted to emotionally?',
  'What am I being guided away from?',
  'What am I being redirected toward?',
  'What am I calling intuition that is actually fear?',
  'What am I calling love that is actually anxiety?',
  'What am I lying to myself about?',
  'What am I making harder than it needs to be?',
  'What am I not seeing clearly about this connection?',
  'What am I outgrowing?',
  'What am I pretending not to care about?',
  'What am I refusing to admit to myself?',
  'What am I romanticizing about the past?',
  'What am I still choosing even though it hurts me?',
  'What am I too proud to ask for?',
  'What did this relationship awaken in me?',
  'What do I need from love that I am afraid to ask for?',
  'What do I need to forgive myself for?',
  'What do people misunderstand about me?',
  'What does my anger want me to understand?',
  'What does my heart already know but refuse to admit?',
  'What does my intuition already know?',
  'What does this repeating situation mean?',
  'What door is opening for me?',
  'What emotion is leading me today?',
  'What energy am I carrying into today?',
  'What energy is coming toward me?',
  'What energy should I protect myself from?',
  'What excuse has expired?',
  'What fear is hiding behind my current choices?',
  'What friendship pattern am I repeating?',
  'What is being revealed beneath the surface?',
  'What is blocking my discipline right now?',
  'What is changing even if I can’t see it yet?',
  'What is my current spiritual lesson?',
  'What is my current work lesson?',
  'What is my soul trying to learn right now?',
  'What is the hidden imbalance between us?',
  'What is the message of this season of my life?',
  'What is the next chapter of my life about?',
  'What is the universe trying to remove from my life?',
  'What is this relationship trying to teach me?',
  'What is today trying to teach me?',
  'What karmic cycle am I closing?',
  'What kind of opportunity should I say yes to?',
  'What kind of partner am I becoming ready for?',
  'What kind of people should I keep close?',
  'What kind of work fits my nature?',
  'What lesson did this person leave behind?',
  'What money pattern do I need to break?',
  'What omen should I pay attention to?',
  'What opportunity could I miss if I’m distracted?',
  'What part of me is still waiting?',
  'What part of me needs more honesty?',
  'What part of my ambition is fear-based?',
  'What part of my life needs consequences?',
  'What pattern am I repeating in love?',
  'What pattern is secretly controlling me?',
  'What should I avoid today?',
  'What should I focus on this month?',
  'What should I know today?',
  'What should I prepare for?',
  'What should I release before tonight?',
  'What should I say yes to today?',
  'What should I stop chasing in relationships?',
  'What should I stop forcing?',
  'What should I stop wasting energy on?',
  'What should I trust right now?',
  'What sign am I ignoring?',
  'What social mask am I tired of wearing?',
  'What truth is obvious today?',
  'What truth would set me free?',
  'What version of me is dying right now?',
  'What would I know if I stopped defending myself?',
  'What would closure look like for me?',
  'What would help me become more consistent?',
  'What wound is asking for attention?',
  'Where am I betraying myself?',
  'Where am I underestimating myself?',
  'Where do I give too much socially?',
  'Where should I be more careful today?',
  'Who around me drains my energy?',
  'Who deserves more access to me?',
  'Why cant I fully move on?',
  'Why do I attract emotionally unavailable people?',
  'Why do I crave validation so much?',
  'Why do I feel attached even when I know better?',
  'Why do I feel behind everyone else?',
  'Why do I feel emotionally heavy lately?',
  'Why do I feel misunderstood?',
  'Why do I feel stuck professionally?',
  'Why do I keep delaying my own growth?',
  'Why do I keep falling for the same kind of person?',
  'Why do I sabotage love when it gets real?',
  'Why do I still compare everyone to them?',
  'Why does this person affect me so deeply?',
];
