// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_Ac--HUwuC-KmGTZ3n0vbnbtDBOamuU',
    appId: '1:91676554553:web:aaa51bfc286b51794024e8',
    messagingSenderId: '91676554553',
    projectId: 'astrology-guru-app',
    authDomain: 'astrology-guru-app.firebaseapp.com',
    storageBucket: 'astrology-guru-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6ydu-9ZMS292QLYqEhh54p7fuMvdXnw',
    appId: '1:91676554553:ios:21564a991f2538434024e8',
    messagingSenderId: '91676554553',
    projectId: 'astrology-guru-app',
    storageBucket: 'astrology-guru-app.firebasestorage.app',
    iosClientId:
        '91676554553-ronjnn2stfgvj657j28aog81h3t0j612.apps.googleusercontent.com',
    iosBundleId: 'com.example.astrologyGuruApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI_Ac--HUwuC-KmGTZ3n0vbnbtDBOamuU',
    appId: '1:91676554553:web:c9d1b1f45633b17d4024e8',
    messagingSenderId: '91676554553',
    projectId: 'astrology-guru-app',
    authDomain: 'astrology-guru-app.firebaseapp.com',
    storageBucket: 'astrology-guru-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6ydu-9ZMS292QLYqEhh54p7fuMvdXnw',
    appId: '1:91676554553:ios:21564a991f2538434024e8',
    messagingSenderId: '91676554553',
    projectId: 'astrology-guru-app',
    storageBucket: 'astrology-guru-app.firebasestorage.app',
    iosClientId:
        '91676554553-ronjnn2stfgvj657j28aog81h3t0j612.apps.googleusercontent.com',
    iosBundleId: 'com.example.astrologyGuruApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgYByGw7likF5AQvJKV4yIjgrU1ffmo8M',
    appId: '1:91676554553:android:2b97d0f2f3b8b1cb4024e8',
    messagingSenderId: '91676554553',
    projectId: 'astrology-guru-app',
    storageBucket: 'astrology-guru-app.firebasestorage.app',
  );
}
